### ISSUE TITLE
ERROR: ssl_handshake: packet length too long

### ISSUE THREAD

**Issue by Daniel-poket-45** [DeroLuna/dero-miner#1]
Hello, I'm making this issue because I got this following error when running deroluna for the windows version: (deroluna for windows is the binary version available for download in the repository, I didn't compile the source code)

C:\Users\testuser\Desktop>deroluna-miner.exe -w <my wallet adress here> -d localhost:1010

19/02 20:47:06.738 INFO  Version: DeroLuna Miner Beta 1.13
19/02 20:47:06.743 INFO  Server:  localhost:10102
19/02 20:47:06.747 INFO  Wallet:  dero1qync6prkg53f456y95rfuq5tn6msrs3aaccmwqlgl7sh4sjz6fgagqgw8mfpv
19/02 20:47:06.753 INFO  Threads: 4
19/02 20:47:06.756 INFO  Dev fee: 10%

19/02 20:47:06.760 INFO  Connecting (localhost:10102)
19/02 20:47:08.813 ERROR ssl_handshake: packet length too long (SSL routines)
19/02 20:47:08.818 ERROR Lost connection (localhost:10102). Reconnect...

well, I tried to find out what ssl is and I didn't understand very well, but deroluna is giving this error on other machines that I have tested within my network, if anyone can help me with this, I would be very grateful :3

**Comment by DeroLuna** [comment]
The mining port is 10100 by default
